### ISSUE TITLE
Update GLIBC version

### ISSUE THREAD

**Issue by cestef** [messense/homebrew-macos-cross-toolchains#14]
The toolchains are currently using GLIBC `2.17`, which is getting pretty old. Would you mind updating and maybe re-building the toolchains with a newer version ? (atleast `2.30` I guess)

**Comment by messense** [comment]
No, the toolchain use low GLIBC version to be compatible with wide range of OSes, the next GLIBC version would be `2.28` IMO which is RHEL 8.

https://github.com/mayeut/pep600_compliance#distro-compatibility
