### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by hzy** [messense/homebrew-macos-cross-toolchains#16]
Are there any plans to support windows?

**Comment by messense** [comment]
No.

**Comment by hzy** [comment]
@messense Sorry for replying on a closed issue.
My expression may not have been clear enough and some details were omitted leading to misunderstanding.
My original feature request was to support cross-compilation on macOS with Windows as the target. Can this feature request be reconsidered?

**Comment by messense** [comment]
It's pointless since you can't build a MSVC cross compiler, for Mingw you can already install it from Homebrew: `brew install mingw-w64`.

**Comment by hzy** [comment]
Indeed,  `mingw-w64` works. But `mingw-w64` package provides toolchain with different naming rule with rust target triples, which from my personally point of view is weird.

**Comment by messense** [comment]
You got to accept that not everything is built around Rust, they use their own naming rules for good reason.
