### ISSUE TITLE
Cross toolchains for ARMv6

### ISSUE THREAD

**Issue by Eygem** [messense/homebrew-macos-cross-toolchains#3]
Hi, I am wondering if you could consider to create cross toolchains for ARMv6.
Raspberry PI Zero W is still very popular and it is built on Broadcom BCM2835. This chipset is based on ARM1176JZF-S, an ARMv6 with Vector Floating-Point (VFP) coprocessor support.
Thank you!

**Comment by messense** [comment]
So I guess the target triples are `arm-unknown-linux-gnueabi` and `arm-unknown-linux-gnueabihf`?

**Comment by messense** [comment]
`arm-unknown-linux-gnueabi` and `arm-unknown-linux-gnueabihf` added for x86_64 macOS, having trouble compiling them for aarch64 macOS.
