### ISSUE TITLE
Compiling wayland

### ISSUE THREAD

**Issue by cybersoulK** [messense/homebrew-macos-cross-toolchains#33]
I love this toolchain, but it's not allowing me to compile wayland (x86_64-unknown-linux-gnu). (for winit crate)
I built all of the static dependencies. but after all of the work, i get this error:

/opt/homebrew/Cellar/x86_64-unknown-linux-gnu/11.2.0_1/toolchain/bin/../lib/gcc/x86_64-unknown-linux-gnu/11.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld.bfd: /.../target/x86_64-unknown-linux-gnu/release/deps/client-121e9c1e029dde09.wayland_cursor-be93a5b041baed8e.wayland_cursor.cb7deed4606e46fe-cgu.0.rcgu.o.rcgu.o: in function `wayland_cursor::CursorTheme::load_from_name':
          wayland_cursor.cb7deed4606e46fe-cgu.0:(.text._ZN14wayland_cursor11CursorTheme14load_from_name17hdb19799281c1b6e7E+0x60): undefined reference to `memfd_create'
          collect2: error: ld returned 1 exit status
          
   any clues?

**Comment by messense** [comment]
`memfd_create` requires glibc 2.27: https://man7.org/linux/man-pages/man2/memfd_create.2.html#top_of_page

This toolchain currently uses glibc 2.17 for maximum compatibility. We'll upgrade to glibc 2.28 after 2024-06-30.

**Comment by cybersoulK** [comment]
@messense someone else suggested me cargo-zigbuild. i was not aware of it previously, but it works for me now! 
I wonder what is the difference between the two projects.
