### ISSUE TITLE
Missing rcrt1.o

### ISSUE THREAD

**Issue by jkroepke** [messense/homebrew-macos-cross-toolchains#36]
Compile with `--static-pie` results into an error:

> /Users/jok/go/go1.22.0/pkg/tool/darwin_amd64/link: running x86_64-linux-gnu-gcc failed: exit status 1
> /usr/local/Cellar/x86_64-unknown-linux-gnu/11.2.0_1/toolchain/bin/../lib/gcc/x86_64-unknown-linux-gnu/11.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld.bfd: cannot find rcrt1.o: No such file or directory
 >collect2: error: ld returned 1 exit status

**Comment by messense** [comment]
It seems that crosstool-ng could have trouble building glibc with --enable-static-pie`: https://github.com/crosstool-ng/crosstool-ng/issues/1193.

Closing as not planned, but feel free to send a PR if you can make it work.
