### ISSUE TITLE
Consider bumping Linux kernel versions

### ISSUE THREAD

**Issue by nox** [messense/homebrew-macos-cross-toolchains#39]
I would like to use the new fields from `tcp_info` when cross-compiling from macOS.

By the way I'm not sure I understand [this commit](https://github.com/messense/homebrew-macos-cross-toolchains/commit/7fcef5f9cb0a9760806ddd566517193d7a916c65), as it seems it downgraded Linux kernel from 5.10 (which does have the new fields I need) to 4.16 (which doesn't).

**Comment by messense** [comment]
I'll do this in July after CentOS 7 EOL when bumping glibc version.

**Comment by vedantmgoyal9** [comment]
@messense
