### ISSUE TITLE
`GLIBC_2.29' not found

### ISSUE THREAD

**Issue by mhfowler** [messense/homebrew-macos-cross-toolchains#4]
Hey this collection has been really helpful, thanks for making it! 

I'm running into an issue, using this to cross-compile rust for aarch64-unknown-linux-gnu. 

Was wondering if you might have any ideas. 

Simple hello world binary works with the cross-compilation. But a more complicated cross-compiled project gives me this error, when I run the cross-compiled binary on my target hardware (which is actually Debian running on a raspberry pi, in aarch64):

```
/lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by ./peach-dyndns-updater)
```

Cross-compiling the same binary from a linux machine to the target machine, and it works fine. So there must be something about the cross-compilation from my mac machine, but I'm not sure what it is. Any idea how to ensure that GLIBC_2.29 is included? I'm using this toolchain from the releases https://github.com/messense/homebrew-macos-cross-toolchains/releases/download/v10.3.0/aarch64-unknown-linux-gnu-aarch64-darwin.tar.gz

**Comment by messense** [comment]
For the GLIBC thing I recommend you read https://www.python.org/dev/peps/pep-0513/#rationale .

I'm not sure why your binary use `GLIBC_2.29` symbols, the toolchain was compile with glibc 2.17.

https://github.com/messense/homebrew-macos-cross-toolchains/blob/558b4ea4d338802ad61636b7f5919b052794be8d/aarch64-unknown-linux-gnu/.config#L405
