### ISSUE TITLE
android clang compiler

### ISSUE THREAD

**Issue by jianshu93** [messense/homebrew-macos-cross-toolchains#44]
Hi Team,

I was cross compiling packages to aarch64-linux-android, but I always got the following error:

Found: Failed to find tool. Is `aarch64-linux-android-clang` installed?

I am not sure this is the compiler from Android studio or it is the system level compiler that is needed. 

Thanks,

Jianshu

**Comment by messense** [comment]
There is no dedicated android target support in this project.
