### ISSUE TITLE
Consider emitting build IDs by default

### ISSUE THREAD

**Issue by umanwizard** [messense/homebrew-macos-cross-toolchains#47]
If you pass `--enable-linker-build-id` to GCC's configure script, the resulting GCC will automatically add the `NT_GNU_BUILD_ID` note to compiled binaries.

This is required by various tools (debuggers, profilers, etc.) and is already the default for the gcc distributed with popular Linux distros like Debian, Fedora and Ubuntu. Thus, it can be confusing for users that it is missing on the versions of GCC installed via this tap.

**Comment by messense** [comment]
I think this is done in #46 by setting `CT_CC_GCC_BUILD_ID=y`.
