### ISSUE TITLE
gfortran wanted!

### ISSUE THREAD

**Issue by zhouzq-thu** [messense/homebrew-macos-cross-toolchains#7]
Please:
- Toggle on gfortran
- Toggle on libgomp, libssp, libquadmath, libsanitizer

**Comment by messense** [comment]
What are the use cases?

**Comment by zhouzq-thu** [comment]
- Some packages are programmed by fortran.
- The official [gcc-linaro toolchains](https://releases.linaro.org/components/toolchain/binaries/latest-7/) contain these features.
